Name = input("Enter your name: ")
Age = int(input("Enter your age: "))
Dob = input("ENter your DOB: ")
Email = input("Enter your email id: ")
SSlc_mark = int(input("Enter your 10th mark: "))
Hsc_mark = int(input("Enter your 12th mark: "))
Father_name = input("ENter your father name: ")
Mother_name = input("Enter your mother name: ")
Mobile_numer = int(input("Enter your mobile number: "))
BloodGrp = input("Enter your blood group: ")
Location = input("ENter your location: ")
Address = input("Enter your address: ")

print("Employee Details")
print(f"{"Name"}: {Name}")
print(f"{"Age"}: {Age}")
print(f"{"Date of Birth"}: {Dob}")
print(f"{"Email ID"}: {Email}")
print(f"{"10th Mark"}: {SSlc_mark}")
print(f"{"12th Mark"}: {Hsc_mark}")
print(f"{"Father Name"}: {Father_name}")
print(f"{"Mother Name"}: {Mother_name}")
print(f"{"Mobile Number"}: {Mobile_numer}")
print(f"{"Blood Group"}: {BloodGrp}")
print(f"{"Location"}: {Location}")
print(f"{"Address"}: {Address}")
