Name = input("Enter your name :")
Age = int(input("Enter your age :"))
Dob = (input("Enter your Dob :"))
Email=(input("Enter your email id :"))
SSlc_mark=int(input("Enter your 10th mark :"))
Hsc_mark=int(input("ENter your 12th mark :"))
print("Personal Details :")
Father_name = input("ENter your father name :")
Mother_name = input("ENter your mother name :")
Mobile_numer= int(input("Enter your mobile number :"))
BloodGrp=input("ENter your blood group :")
Location = input("Enter  your location :")
Address=input("ENter your address :")



print("Your name is :",Name)
print("Your age is :",Age)
print("Your dob is :",Dob)
print("Your email is :",Email)
print("your sslc mark is :",SSlc_mark)
print("your hsc mark is :",Hsc_mark)
print("your father name is :",Father_name)
print("your mother name is :",Mother_name)
print("your mobile number is :",Mobile_numer)
print("your blood grp is :",BloodGrp)
print("your location  is :",Location)
print("your address  is :",Address)
